services:
  - type: web
    name: pixelds-backend
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 4000
